ingredients:
- 1/2 cup coarse fresh breadcrumbs made from crustless country-style bread
- 5 teaspoons dijon mustard, divided
- 2 teaspoons plus 1 tablespoon olive oil
- 1/2 teaspoon mustard seeds
- 1 9-ounce package fresh spinach leaves
- 3 tablespoons half and half
- 1 teaspoon chopped fresh thyme
- 2 large eggs
- Fresh thyme sprigs (for garnish)

prep:
- Preheat oven to 400°F. Toss crumbs with 2 teaspoons mustard, 2 teaspoons oil, and mustard seeds in medium bowl to coat.
- Scatter on rimmed baking sheet. Bake until golden and crisp, 6 to 8 minutes.
- Meanwhile, add enough water to deep large nonstick skillet to cover bottom. Add spinach; toss over high heat to wilt, about 2 minutes. Scrape into sieve set over bowl; press out liquid. Wipe out skillet; reserve.
- Transfer spinach to medium saucepan. Add 3 teaspoons mustard, half and half, and chopped thyme. Stir over medium heat until thick, about 3 minutes. Season with freshly ground black pepper. Remove from heat.
- Heat remaining 1 tablespoon oil in reserved skillet over medium-high heat. Crack eggs into skillet, spacing apart. Fry until whites are cooked through, 3 to 4 minutes. Divide spinach between 2 plates, spreading out as base for eggs. Top with eggs, crumbs, and thyme sprigs.
 
other:
Sunny-Side-up Eggs on Mustard-Creamed Spinach with Crispy Crumbs  Recipe
 at Epicurious.com
home › recipes & menus ›
                sunny-side-up eggs on mustard-creamed spinach with crispy crumbs
welcome epicurious user ·
my recipe box ·
my profile ·
preferences ·
sign out
Not a member?  To save, rate, and share recipes, join now !  Already a member? sign in
win best oscar party
 
get the epicurious iPhone app Close
host a glittering night
more stories on epicurious...
Menus inspired by the ten Best Pictures ›
Hollywood party planner reveals her secrets ›
Making popcorn? We name the tastiest brands ›
Recipes & Menus ›
print print
full page
full page w/ photo
3x5 card
4x6 card
shopping list
 
e-mail e-mail
recipe
shopping list
font size: A A A
Sunny-Side-up Eggs on Mustard-Creamed Spinach with Crispy Crumbs Bon Appétit  | February 2011
by The Bon Appétit Test Kitchen
recipe
reviews ( 8 )
photo
video
my notes
find out more
user rating 67% would make it again
user rating:
Sunny-Side-up Eggs on Mustard-Creamed Spinach with Crispy Crumbs 3½ forks
rate this recipe review this recipe
at a glance main ingredients Mustard ,  Breadcrumbs ,  Egg ,  Spinach
type Quick & Easy
dietary considerations Vegetarian ,  Low Cal ,  High Fiber
see all about: Vegetarian Cooking ,
Quick & Easy Cooking
more resources Food Dictionary cooking videos
enlarge image
yield: Makes 2 servings
