---
- 3 tablespoons extra virgin olive oil
- 2 medium fennel bulbs, trimmed fronds reserved, thinly sliced
- 2 1/4 pounds / 36 ounces farmer market carrots, thickly sliced
- 2 large cloves garlic, thinly sliced
- 10 cups good-tasting vegetable broth or water
- salt to taste
- 3 cups / 12 oz cooked wild rice
- 2 tablespoons blood orange olive oil or 5 tablespoons fresh orange juice
- lots of freshly grated Parmesan cheese
